admin:
    resource: "@AdminBundle/Controller"
    type:     annotation
    prefix:   /

cms:
    resource: "@CmsBundle/Controller"
    type:     annotation
    prefix:   /

slug:
    resource: "@SlugBundle/Controller"
    type:     annotation
    prefix:   /

seo:
    resource: "@SeoBundle/Controller"
    type:     annotation
    prefix:   /

menu:
    resource: "@MenuBundle/Controller"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller'
    type: annotation
