<?php

namespace GlgProductions\CmsBundle\Repository;

/**
 * SiteSettingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiteSettingRepository extends \Doctrine\ORM\EntityRepository
{
}
